import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HomeNavbar from "./commons/HomeNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <section className="bg-[#D9D9D9] py-7">
          <div className="w-[80%] mx-auto">
            <HomeNavbar />
          </div>
        </section>
        <section className="">{children}</section>
      </body>
    </html>
  );
}
