import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HomeNavbar from "./commons/HomeNavbar";
import { usePathname } from "next/navigation";
import GeneralNavbar from "./commons/GeneralNavbar";
import { headers } from "next/headers";
import { StoreProvider } from "./utils/providers/StoreProvider";
import SessionProvider from "./utils/providers/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mimotar",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const headersList = headers();
  // const pathname = headersList.get("x-invoke-path") || "";
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <SessionProvider session={session}>
          <StoreProvider>
            <section className="">{children}</section>
          </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
